<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Monitoring.Api</RootNamespace>
    <AssemblyName>Monitoring.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monitoring.Application\Monitoring.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Web\BuildingBlocks.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
