<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <RootNamespace>Files.Application</RootNamespace>

    <AssemblyName>Files.Application</AssemblyName>

  </PropertyGroup>



  <ItemGroup>

    <ProjectReference Include="..\Files.Domain\Files.Domain.csproj" />

    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />

  </ItemGroup>



  <ItemGroup>

    <PackageReference Include="FluentValidation" Version="11.11.0" />

    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />

    <PackageReference Include="MediatR" Version="12.4.1" />

    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />

  </ItemGroup>



</Project>

