<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <RootNamespace>Notifications.Api</RootNamespace>

    <AssemblyName>Notifications.Api</AssemblyName>

  </PropertyGroup>



  <ItemGroup>

    <FrameworkReference Include="Microsoft.AspNetCore.App" />

  </ItemGroup>



  <ItemGroup>

    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />

    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Web\BuildingBlocks.Web.csproj" />

  </ItemGroup>



</Project>

