<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AsyncTasks.Application</RootNamespace>
    <AssemblyName>AsyncTasks.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsyncTasks.Domain\AsyncTasks.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
