<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <RootNamespace>Files.Api</RootNamespace>

    <AssemblyName>Files.Api</AssemblyName>

  </PropertyGroup>



  <ItemGroup>

    <FrameworkReference Include="Microsoft.AspNetCore.App" />

  </ItemGroup>



  <ItemGroup>

    <ProjectReference Include="..\Files.Application\Files.Application.csproj" />

    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Web\BuildingBlocks.Web.csproj" />

  </ItemGroup>



</Project>

