<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <RootNamespace>Files.Domain</RootNamespace>

    <AssemblyName>Files.Domain</AssemblyName>

  </PropertyGroup>



  <ItemGroup>

    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />

  </ItemGroup>



</Project>

